### PR TITLE
[Feature] Add optional levels to product order book

### PR DESCRIPTION
**Pull request by dougdellolio**

### CODE REVIEW

**Comment by jonnii** [comment]
@dougdellolio why is there a guid in the response?

**Comment by jonnii** [comment]
Oh wait I see now. I'd make these different api calls and maybe have the content of the array deserialized into a specific type? e.g. this `[200, 100, 'da863862-25f4-4868-ac41-005d11ab0a5f'],` would get deserialized into a type with Price, Size and Order Id.

**Comment by dougdellolio** [comment]
@jonnii What is the best way to do this with Json.net? Would I need to create a `CustomerConverter` since the API returns just a collection of values?

**Comment by jonnii** [comment]
i think so?

**Comment by dougdellolio** [comment]
@jonnii going to merge this for now. ran into some weirdness around the custom converter, but the result is still transformed into `Bid` and `Ask`.

**Pull request merged**
