### PR TITLE
dotnetcore2.0 migration, PlaceLimitOrderAsync() fix, documentation updates

### PR DESCRIPTION
**Pull request by confessore**
migrated to dotnetcore2.0, fixed PlaceLimitOrderAsync() to properly utilize TimeInForce GoodTillTime, added GoodTillTime to the TimeInForce enumeration, updated GDAXClient.Specs to include these changes, updated README

### CODE REVIEW

**Comment by confessore** [comment]
not too intimately familiar with continuous integration or Machine.Specifications. works great on my linux vps, maybe I'm missing a package?

**Comment by confessore** [comment]
maybe this is because dotnetcore2.0 does not generate a packages folder on build?

**Comment by confessore** [comment]
library outputs to /bin/Release/netcoreapp2.0/ rather than /bin/Release/

believe that TravisCI is not finding the library due to this reason

**Comment by dougdellolio** [comment]
Hey @confessore. These changes are awesome! Apologies for the delayed responses as I am currently without power and have no computer access....  

To help me understand each change here fully could you possibly break the fixes (especially the placelimitorder one) into smaller pull requests as 112 files is not easy to review. It will also help lower the chances of breaking things. Hopefully this won’t be too much more work on your side. 

Also regarding the net core migration. My intention was to port this to net standard to allow the user to target either core or framework. What are your thoughts surrounding this?

All much appreciated :)

**Pull request closed without merging**
